### ISSUE TITLE
ToSql and FromSql Traits for uint primitives

### ISSUE THREAD

**Issue by gcarq** [jgallagher/rusqlite#117]
How much effort would it be to implement ToSql and FromSql traits for c_uint, u32 and u64?

**Comment by jgallagher** [comment]
Rusqlite doesn't provide it itself because SQLite doesn't provide support for unsigned values in its C API; it's not clear how to handle u64 in particular (c_uint and u32 could be stored as signed 64-bit values as long as you added range checks in `FromSql::column_result`). There's some discussion of options for storing u64s in SQLite on stack overflow (e.g., http://stackoverflow.com/questions/8496730/binding-an-unsigned-long-uint64-in-an-sqlite3-statement-c). All of the solutions proposed should be implementable, but which one is appropriate will depend on what you need.

**Comment by jgallagher** [comment]
@gcarq I'm going to close this issue for now, since I don't think there's much we can do here given SQLite's API.
