### ISSUE TITLE
A question about the implementors in rusqlite::types::FromSql

### ISSUE THREAD

**Issue by Outpox** [jgallagher/rusqlite#209]
Hey there ! 

I was retrieving some data from a local database and tried to store them in f32 but was given the following error :  
```
error[E0277]: the trait bound `f32: rusqlite::types::FromSql` is not satisfied
```
So I checked the `rusqlite::types::FromSql` documentation and I noticed only f64 was implemented. 
I then went to check the [sqlite3 datatypes](https://www.sqlite.org/datatype3.html) only to notice that REAL value are _stored as an 8-byte IEEE floating point number_.   
So my question is, why doesn't the trait implement the type in the sqlite doc as i8 (integer are being _stored in 1, 2, 3, 4, 6, or 8 bytes_) or f32?  

I'm new to Rust and have never really done any C/C++ so that might be a dumb question.

**Comment by jgallagher** [comment]
Howdy! I think there are two questions there (one about integers and one about floats).

The float question is easier - a Rust `f32` is a 32-bit (or 4-byte) float. Since SQLite floats are 8 bytes (64 bits), we only provide `FromSql` for `f64`. You could implement `FromSql` for `f32` if it makes sense for your project, but in general that interface would force us to provide a `FromSql` that was losing precision from the values we get from SQLite.

Integers are a little more complicated. SQLite may well store them in 1, 2, 3, 4, 6, or 8 bytes, but the only interfaces it exposes for us to get integer values return a C int via `sqlite3_value_int` or a 64-bit (8 byte) integer via `sqlite3_value_int64` (from [Obtaining SQL Values](https://www.sqlite.org/c3ref/value_blob.html)). The size of `int` in C can vary from platform to platform. On most (all?) modern desktop/server systems it's 32 bits (4 bytes), but it can be smaller on some embedded hardware.

You could make a case that we should really only provide `FromSql` for `i64` (8 byte integers), but since `i32` is so common, we do go ahead and provide that one too. The `i32` `FromSql` will misbehave if integer values outside its range are being fetched, though. `FromSql` for other integer sizes (like `i8`) could be provided as well, but they'd have the same issue of silently truncating values if you tried to fetch values outside their range.

**Comment by jgallagher** [comment]
On second thought - our impl of `FromSql` for `i32` should be checking that the value is in range (it's not currently). If we had that check in place, it'd be fine to add support for the other integral types as well. I'll leave this issue open until that can be addressed. `f32` is still out in the cold, though. If you're fine with the potential loss of precision, you can always get an `f64` then use `as f32` to convert it.

**Comment by Outpox** [comment]
Thanks for this excellent answer, it now makes sens to me that you implemented it this way. I was expecting something along those lines.  
  
Also thanks for the library, it's been very easy to use for me!
