### ISSUE TITLE
SQLCipher support

### ISSUE THREAD

**Issue by rnewman** [jgallagher/rusqlite#219]
SQLCipher is a extension to SQLite that provides transparent AES-256 encryption of the database file. It uses OpenSSL to do so.

The only changes to SQLite's API are the addition of `int sqlite3_key(sqlite3 *db, const void *pKey, int nKey);` and `sqlite3_rekey(sqlite3 *db, const void *pKey, int nKey)`, which are both also exposed through `PRAGMA` directives.

I expect that whoever tackles https://github.com/mozilla/mentat/issues/118 will end up here for guidance; @jgallagher, I'd very much appreciate your opinion on how, and whether, this should integrate with rusqlite.

I would be interested to see any or all of the following in rusqlite:

- A Cargo feature to use SQLCipher instead of mainline SQLite as the bundled library. (In theory SQLCipher can simply replace SQLite — it's a strict superset — but I don't know what the build or license implications are.)
- The two key functions (and any errors they expose) wrapped in Rust. This should be fairly safe to leave even for non-SQLCipher consumers.
- Mention in the build documentation of how to get started linking against SQLCipher instead of SQLite.

**Comment by jgallagher** [comment]
I think the technical changes required for this are relatively small; the licensing bit is the tricky part. Technical things that are definitely doable include:

* Adding a cargo feature to `rusqlite` that would expose Rust functions for `sqlite3_key` and `sqlite3_rekey`.
* Adding a cargo feature to `libsqlite3-sys` (that could be transitively set by rusqlite) to change [build.rs](https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/build.rs) to look for libsqlcipher instead of libsqlite3 in non-bundled mode. (IANAL but I think there are no licensing issues with this kind of change to rusqlite, although any program using this feature would itself need to abide by SQLCipher's requirements.)

I'm not sure how to handle the `bundled` feature, though. If I'm reading the [licensing requirements](https://www.zetetic.net/sqlcipher/open-source/) correctly we could bundle the community edition with appropriate language about that feature (again this would require that programs using this feature follow the requirements themselves). Another option would be to let users specify their own amalgamated source file for the `bundled` option. It's not clear to me whether SQLCipher's commercial offerings come with source; if they do it seems like we'd pretty much have to take the latter option to support those.

**Comment by rnewman** [comment]
I imagine one way to do the 'bundling' is to provide the equivalent of `libsqlite3-sys` but using an feature-led external crate (still statically linked). That separate repo can deal with all of the license stuff, and the end consumer would still be responsible for including the user-visible license details. Consuming libraries would only need to set the feature, rather than providing library source.

I believe the Cargo manifest would allow that:

```
[dependencies]
libsqlcipher-sys = { optional = true, version = "…" }

[features]
bundled-sqlcipher = ["libsqlcipher-sys"]
```

**Comment by jgallagher** [comment]
That's definitely worth investigating, but there are some sharp corners that would need smoothing -

* what's the effect of having two possible `-sys` crates on the `rusqlite` code itself?
* how difficult is it to keep the two `-sys` crates' APIs in sync?
* if we used a feature like you describe, we would need to also exclude `libsqlite3-sys` when that feature is used. I'm sure this is possible but don't know off the top of my head if it's easy or how it plays with all the other Cargo features we have.

I suspect solving these might be more painful than adding options to support SQLCipher (and appropriate licensing) to `libsqlite3-sys`. Not sure though.

**Comment by gwenn** [comment]
[SQLCipher](https://github.com/sqlcipher/sqlcipher/blob/master/README.md) uses the API exposed for the [SQLite Encryption Extension](http://www.hwaci.com/sw/sqlite/see.html).
It seems sensible to not depend on SQLCipher but support any encryption extension.
Regards.

**Comment by chshawkn** [comment]
SQLCipher API https://www.zetetic.net/sqlcipher/sqlcipher-api/

**Comment by rtilder** [comment]
Perhaps the most weighty reason for a separate libsqlcipher-sys crate is the three crypto library options supported and the various tweaks needed to get some of them to build.  Building against CommonCrypto with just gcc needs some frameworks added to the command line and OpenSSL on OS X these days usually needs cpp and linker options to find crypto.h and libcrypto.  I'm not certain how to pass those latter on in a configurable manner other than doing something like HeaderLocation method you currently use for wrapper.h  While the build defaults to use OpenSSL, that might be an ill advised go-to for all platforms since Apple has deprecated OpenSSL in its releases.

I've got a libsqlcipher-sys crate building correctly but it's really just a simplified derivative of libsqlite3-sys/build.rs.  @jgallagher, I'll have a further look at what it would take to exclude libsqlite3-sys like you mentioned in your last comment but I'm a total Cargo newbie.

**Comment by gwenn** [comment]
Would you mind if I close this issue (fixed in 0.13.0 release) ?

**Comment by thomcc** [comment]
We're using sqlcipher with rusqlite in https://github.com/mozilla/mentat (well, behind the `sqlcipher` feature). It complicates the build process and is hardly as seamless as with SQLite, but it's pretty clearly workable so it seems reasonable to close this to me.

**Comment by Dygear** [comment]
Please forgive the question on an already closed PR, but this seems to be the only place that talks about [SQLite's Encryption Extension (SEE)](http://www.hwaci.com/sw/sqlite/see.html). For people like myself who purchased the SQLite Encryption Extension, is it possible to tell `libsqlite3-sys` with to use my SEE amalgamated source file?

We are given these files ([Per this page](https://sqlite.org/see/doc/release/www/readme.wiki)):
  1. sqlite3-see-aes256-openssl.c
  2. sqlite3-see-aes256-cryptoapi.c
  3. sqlite3-see-aes256-ofb.c
  4. sqlite3-see-cccrypt.c
  5. sqlite3-see-aes128-ofb.c
  6. sqlite3-see-aes128-ccm.c
  7. sqlite3-see.c
  8. sqlite3-rc4.c
  9. sqlite3-xor.c

It seems most correct to take the `sqlite3-see-aes256-openssl.c` file, rename it to `sqlite3.c` and compile against that. But how do I tell `rusqlite` / `libsqlite3-sys` to use my file to compile?

**Comment by thomcc** [comment]
You'll probably have to compile it to a library and use SQLITE3_INCLUDE_DIR and SQLITE3_LIB_DIR to tell rusqlite to use it. This issue is unrelated to SEE, SQLCipher and SEE are not the same.
