### ISSUE TITLE
What should we do when running with a SQLite version older than the one we ran bindgen against?

### ISSUE THREAD

**Issue by jgallagher** [jgallagher/rusqlite#225]
This came up on #221 where `SQLITE_LIMIT_WORKER_THREADS` is exposed by rusqlite but unknown if we run linked against a SQLite older than 3.8.7. I'm not sure how we should address this. Options:

* Do nothing (current "strategy")
* Do nothing but attempt to document any exposed features newer than X (some SQLite version that predates what we think the vast majority of platforms ship with)
* Throw an error (when opening new connections?) if the SQLite version is older than X. X here would almost certainly have to be something older than the version we bundle with and run bindgen against - otherwise no one would be able to use their platform-provided libsqlite; this still leaves the problem of what to do if we expose or expect something between X and our bundled version.
* Add SQLite version checks to any rusqlite functions that use features newer than SQLite version X, and return errors from those functions if they're called. E.g. for #221, we could change `limit()`/`set_limit()` to return `Result<i32>` and fail with something like a `SqliteVersionOutdated` error if the caller tried to use `SQLITE_LIMIT_WORKER_THREADS` with a SQLite older than 3.8.7.

The last one seems like the best but also the most work (by far). @gwenn or @rnewman any thoughts?

**Comment by rnewman** [comment]
Random thoughts:

This is a little tricky, because all of these avenues allow for runtime failures (by definition). As such, I think documentation must be at least part of the solution: a developer testing against new SQLite won't find bugs no matter what you do. A developer who _really_ wants to avoid risk will statically link.

Furthermore, a developer expecting to use a system-provided library must be prepared for it to be old, so I don't think it's worth you jumping through too many hoops. For example, Firefox for iOS relies on partial index support, [and checks for it](https://github.com/mozilla-mobile/firefox-ios/blob/master/Storage/SQL/BrowserTable.swift#L122).

I think it's only appropriate for rusqlite to itself handle errors or document individual feature incompatibilities if it's exposing functionality that is more than just a passthrough.

SQLite 3.9.0 and later use semver, at least, so you could robustly check for incompatibilities in newer versions.

3.8.7 is more than two years old. However, Android versions are renowned for shipping old SQLite: Firefox for Android, for example, runs on devices that ship 3.7.x. That means you can't ignore the problem completely.

My proposal:
- Rely on SQLite's own backward-compatibility efforts. As I understand it, #221 simply retrieves `-1` because SQLite doesn't understand a limit — it doesn't fail. That's OK.
- Check semver compatibility once at runtime. A warning on stderr is appropriate, but erroring would be fine too.
- Document as best you can. Print a message of caution during bindgen or at compile-time if that's idiomatic and appropriate (and possible!).
- Panic (with a good message?) if necessary.

**Comment by jgallagher** [comment]
> I think it's only appropriate for rusqlite to itself handle errors or document individual feature incompatibilities if it's exposing functionality that is more than just a passthrough.

My main concern here is whether it's possible rusqlite is exposing an incorrect or even unsafe interface if linked against an older SQLite. Conceptually it's very easy to imagine this happening one of two ways:

* We pass some valid-in-newer-SQLite-but-invalid-in-older-SQLite (like #221). Probably SQLite's robustness against misuse (even at the C API layer) is sufficient here, and calls will either safely fail at runtime (with something like the `SQLITE_MISUSE` error code) or fail in some harmless way (like `-1` on #221).
* We expect something based on the behavior of new SQLite that isn't what we get from old SQLite, leading to broken assumptions in `unsafe` code that bubble up and break things. I don't _think_ rusqlite makes any assumptions beyond the C types, so maybe we're ok here too.

A less pressing concern is if we try to link against functions that are newer than the oldest version anyone tries to use rusqlite with. I think this will fail at link time; if it comes up we can probably address it with cargo features.

> Check semver compatibility once at runtime.

Is this possible if we're going _backwards_ in semver? I could see a check for "we ran bindgen against 3.16, you're running 3.19, we're good", but it doesn't seem possible to do the opposite.

> Print a message of caution during bindgen or at compile-time if that's idiomatic and appropriate (and possible!).

I don't think this is possible the way we currently build rusqlite - we don't even run bindgen as part of the build process currently.

**Comment by rnewman** [comment]
> Is this possible if we're going backwards in semver? I could see a check for "we ran bindgen against 3.16, you're running 3.19, we're good", but it doesn't seem possible to do the opposite.

I think one can check in both directions (after SQLite 3.9.0, anyway). There are only two cases we need to worry about:

1. The major version changed from bindgen to runtime, either up or down. This is never supported, for obvious reasons.
2. The minor version is smaller at runtime than at bindgen time. That is: a consumer of rusqlite might be using new SQLite functionality that was introduced in a backwards-compatible way, but naturally isn't supported in the older version. This is not guaranteed to be a problem, but it's worth warning about.

It's fine for the minor version to be higher at runtime.

Your fourth suggestion, in these terms, is essentially to check more carefully for incompatibilities in the case of a minor version bump, right?

Note that your earlier concerns _should_ be addressed by semver…

**Comment by jgallagher** [comment]
> The minor version is smaller at runtime than at bindgen time. That is: a consumer of rusqlite might be using new SQLite functionality that was introduced in a backwards-compatible way, but naturally isn't supported in the older version. This is not guaranteed to be a problem, but it's worth warning about.

Right, I suppose all of my concern is right here. "Not guaranteed to be a problem" makes me nervous if I can't say "and if there _is_ a problem, rusqlite is still safe (in the Rust sense) and this is what could happen". I think I'm convinced that if both SQLite and rusqlite are correct this is still safe, and the "what could happen" includes at least link time errors, unexpected (but presumably harmless) return values like #221, and SQLITE_MISUSE-style error returns.

I'm also not sure how to provide this warning. Libraries that print to stderr bug me, but maybe I could do that by default and provide a hook to silence it?

> Your fourth suggestion, in these terms, is essentially to check more carefully for incompatibilities in the case of a minor version bump, right?

Yes, exactly. Instead of giving a warning when we check the version, return errors from any functions that we know won't work correctly. Not sure it's worth it though given the rest of this thread.
