### ISSUE TITLE
Allow retrieving borrowed values from a row

### ISSUE THREAD

**Issue by aidanhs** [jgallagher/rusqlite#259]
Currently, if I want to deserialize a blob it seems (correct me if I'm wrong) that I need to either

1. retrieve a `Vec<u8>`, and then pass that to a deserialization function
2. do the dance to retrieve a blob as a reader

I would like to propose allowing

3. retrieving the borrowed value of a row (i.e. a `&[u8]`)

Looking at the `FromSql` trait, I'm not sure it's possible to do it within the constraints imposed by that as it stands right now - it expects the return value to have an independent lifetime to the input `ValueRef`. So it seems to me there are three ways to add this:

1. add a lifetime constraint to the `FromSql` trait, which shouldn't affect any existing code (I believe) because no lifetimes are currently returned, to allow returning borrowed values as well
2. create a new trait `FromSqlBorrowed` and appropriate new methods like `get_borrowed` etc
3. add a `get_raw` to `Row` which allows directly retrieving a `ValueRef`

Personally I'm in favour of the first option, as long as I'm correct in my suspicion that it shouldn't affect any existing code.

Thoughts? Have I missed anything?

**Comment by jgallagher** [comment]
I think 1 is harder than it sounds, but haven't spent a lot of time thinking about it. Have you tried adding the constraint?

2 is definitely an option; it came up a while ago when someone wanted to deserialize a blob into a Uuid. We ended up discovering that it wasn't necessary for that (see the last comment on #158). Can you do something like that?

The most annoying thing to deal with here is that if rusqlite allows you to get borrowed memory from a row, it can't let you do anything else with that row as long as the memory could be alive (since getting that same column again as a different type - perfectly legal from SQLite's point of view - would invalidate that memory).
