### ISSUE TITLE
Use `rerun-if-env-changed` in libsqlite3-sys

### ISSUE THREAD

**Issue by Diggsey** [jgallagher/rusqlite#329]
Build scripts which access environment variables should output lines like:
```
cargo:rerun-if-env-changed=PATH
cargo:rerun-if-env-changed=SQLITE3_LIB_DIR
```

To indicate that cargo should rerun the build script if those environment variables change.

Without that, it is confusing for people building crates which depend on this one, because even after they configure their environment, the build will fail until they run `cargo clean`.

**Comment by gwenn** [comment]
Would you mind give #344 a try ?

**Comment by Boscop** [comment]
Is it really necessary to rebuild `libsqlite3-sys` just because `PATH` changed?
I think [this](https://github.com/jgallagher/rusqlite/commit/9178e3f45225e4c07d976a0d144c12e9af3a44d5#diff-bdb38289dd1bd25103fa7ccc4e6b5d87R89) is the cause of my issue https://github.com/jgallagher/rusqlite/issues/435
Would it be possible to exclude `PATH` from the set of env vars used with `rerun-if-env-changed`?

**Comment by gwenn** [comment]
@Boscop [The directories that are listed in the PATH environment variable.](https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-search-order)

**Comment by Boscop** [comment]
@gwenn 
**Please** don't rebuild when the PATH env var changes. It is still SO annoying every day because it massively increases my build times every time when doing cargo check in Sublime and `cargo run` in the console (because [cargo prepends `%HOME%\.cargo\bin` to `PATH` **even if** it's already in `PATH`](https://github.com/passcod/cargo-watch/issues/106#issuecomment-445569998)). 
It causes a rebuild of diesel, migrations_internals, r2d2-diesel, migrations_macros, diesel_migrations and my workspace's crates that depend on diesel. Every time!
It's especially annoying with `cargo watch -x run` and makes cargo-watch unuseable..

(Please at least allow opting out of the rebuild via a feature flag, but better not do this at all, because a feature flag would require using a `[patch]` override.)
