### ISSUE TITLE
Check if the right number of parameters is passed into `query`

### ISSUE THREAD

**Issue by gsingh93** [jgallagher/rusqlite#34]
Currently if you pass a slice with the wrong length into `SqliteStatement::query`, it fails with an [assert](https://github.com/jgallagher/rusqlite/blob/master/src/lib.rs#L636). It would be better to return a `Result`, or at the very least use the `assert!` macro with a second argument as an informative error message.

It seems like `SqliteError` is meant only for errors from the sqlite bindings. If this is the case, it might be messy to add another `Result` into the function interface. You could instead change the `SqliteResult` type alias to take an enum as the error type param that could be either `SqliteError` or some other `Error` object, so both errors could be handled. Or just merge all the errors into `SqliteError`.

**Comment by jgallagher** [comment]
I'd be fine with adding a message to the assert, but `query` should not return a `Result` in this case. Passing in a slice with the wrong length is a programmer error and cannot be recovered from - it's a bug that needs to be fixed.

`SqliteError` should only have errors from the sqlite bindings, because this library only exists to provide sqlite bindings. :) The few times we've needed to construct one, there's been a reasonable choice to make it look like a SQLite error (e.g., using `SQLITE_MISUSE` if we can't convert a path to a C string).

**Comment by gsingh93** [comment]
Makes sense. Having a descriptive error message in the assert should be good enough so people don't have to dig into the code to see what assert failed. You should probably double check any other asserts you have too.
