### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by kornelski** [jgallagher/rusqlite#374]
It's been a while since the last release, and the master branch has a fix I'd like to see released (#367).

cc #339

Could you make a release to crates.io?

**Comment by gwenn** [comment]
As fas as I know, only @jgallagher can make a release.

**Comment by gwenn** [comment]
@kornelski, it seems that you are not the only one waiting for a release: https://github.com/rust-lang/rust/pull/49799
:worried:

**Comment by awakecoding** [comment]
@gwenn +1 on a new release, especially since the virtual table feature has been merged in master :) I would just like to say thanks for your work, we really appreciate it. Long story short, I've had two interns here at @Devolutions (@SalahKmt and @banaru4) work on a project called siquery (system info query) that is pretty much an osquery clone written in Rust. Their internship is coming to an end this week, but they've got something functional already (https://github.com/Devolutions/siquery-rs). This wouldn't have been possible without your work on the virtual tables. Can you contact me in private at mamoreau@devolutions.net? I would like to send a small gift as a token of gratitude.

**Comment by jgallagher** [comment]
@gwenn I believe I added you as an owner on crates.io. Can you see if you got an invite for that and can now push releases? Thanks very much for taking on everything you have!

**Comment by gwenn** [comment]
@jgallagher I've just checked but page says: "You don't seem to have any pending invitations."
I will check again tomorrow and keep you posted.

**Comment by gwenn** [comment]
@jgallagher `rusqlite` is ok now (i guess) but not `libsqlite3-sys`:
```
Uploading libsqlite3-sys v0.9.3 (file:///Users/gwen/Rust/rusqlite-clean/libsqlite3-sys)
error: api errors: this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
```

**Comment by jgallagher** [comment]
Ahh my bad. Try now.

**Comment by gwenn** [comment]
rusqlite 0.14 released
