### ISSUE TITLE
Savepoint borrows mutable Connection

### ISSUE THREAD

**Issue by njaard** [jgallagher/rusqlite#390]
`Savepoint` has the lifetime of a mutable `Connection`, which means that while you hold a `Savepoint`, you can't actually do anything with your `Connection` (or `Transaction`), which makes it useless.

**Comment by gwenn** [comment]
Which makes it safe and not useless because a `Savepoint`/`Transaction` is a `Connection` (`Deref<Target = Connection>`).
https://docs.rs/rusqlite/0.14.0/src/rusqlite/transaction.rs.html#101

See
https://github.com/jgallagher/rusqlite/pull/285
https://github.com/jgallagher/rusqlite/pull/318
https://github.com/jgallagher/rusqlite/pull/322
