### ISSUE TITLE
Using previously prepared statements in transactions

### ISSUE THREAD

**Issue by jneuff** [jgallagher/rusqlite#508]
Is there a way to prepare a statement globally and then use it inside different transactions? Or should I use `prepare_cached` in this case? What are the downsides of using `prepare_cached` vs. keeping a `Statement`?

**Comment by gwenn** [comment]
Yes, you should use `prepare_cached`.
The downsides are (non-exhaustive):
 - cache lookup,
 - cache may not be correctly sized,
 - same query/sql can be cached only one at a time (you can use SQL comment as a workaround).

Another solution is to create transaction manually (`db.execute_batch("BEGIN");` ... `db.execute_batch("COMMIT");`)

**Comment by jneuff** [comment]
Thanks, that makes it clear!

**Comment by gwenn** [comment]
@cisaacson I didn't say that they cannot be used again. They are cached because they are reused.

**Comment by cisaacson** [comment]
Thanks @gwenn . So for this comment:
> same query/sql can be cached only one at a time (you can use SQL comment as a workaround).
If I want to use the same statement 10X in the same TX by calling `prepare_cached` it should work fine then. Seems like I misread it, what you are saying is that you can only *cache* a unique statement once (not sure why we'd ever want to do differently). Do I have it right?

**Comment by gwenn** [comment]
Sorry, I don't have a concrete use case but you may want to repeatedly perform something like that:
```rust
loop {
//...
    let mut stmt1 = db.prepare_cached(sql)?;
    let mut stmt2 = db.prepare_cached(sql)?; // never cached except if sql slightly differs
    let mut rows = stmt1.query([v1])?;
    while let Some(row) = rows.next()? {
        //...
        let mut others = stmt2.query([v2])?;
        //...
    }
}
```

**Comment by cisaacson** [comment]
Thanks @gwenn , looks like it will do just what we need, we can just reuse the cached statements many times for a batch. We'll try it out.

**Comment by e00E** [comment]
This deserves a mention in the docs and maybe an example. I found trying to use prepared statements in transactions confusing.

If you have a prepared statement that you keep in a variable, then you cannot use rusqlite's transaction method. You cannot use it because the method needs mutable access to the connection, which the prepared statement has borrowed. The solution is to manually run the transaction statements (begin, commit, rollback, etc) on the connection. This doesn't require mutable access. You need to carefully ensure that you finish the transaction in all code paths in your function. For example, for any call that can error, you cannot just use the `?` operator. You need to match on the result and send the rollback statement. This is unergonomic and error prone. You can improve this by making a wrapper function that handles the transaction setup.

(I didn't try this part, but I imagine it works like this.) If you have a cached prepared statement, then ergonomics are better because you can get the prepared statement from the cache inside of the transaction. This way you don't run into the problem that the transaction method mutably borrows the connection. The downside is that you incur the overhead of the cache. I prefer storing my prepared statements in variables.

**Comment by greglearns** [comment]
@e00E There is an alternative way to make this work: https://gist.github.com/rust-play/2ed9ffd13aea6c766431c9e7f403c8e7
Basically, you can use transactions and prepared statements the way you probably "expect" to use them, but you must `drop(stmt)` before the `tx.commit()` to fix the borrow error.

**Comment by gwenn** [comment]
Or with nested block:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ac2867248a7cdea433a2d1d98f9c694e
