### ISSUE TITLE
Document why it's necessary for query_map to return an SqliteResult<MappedRows> when MappedRows will itself yield SqliteResults when iterated

### ISSUE THREAD

**Issue by bstrie** [jgallagher/rusqlite#72]
At first blush it seems redundant to have two results in use here, so I'm curious what errors it is actually guarding against.

**Comment by jgallagher** [comment]
Yeah, I'm not really a fan of this, but basically every call into SQLite can fail, so that gets reflected in this interface.

* `query_map` can fail if binding any of the parameters fails (i.e., a call to `sqlite3_bind_XXX`).
* The iterated rows can fail if `sqlite3_step` fails; e.g., if the database file is locked by another connection.

#91 adds documentation for the first point. I'm not sure how to add docs for the second; putting a doc comment on the `fn next` implementation didn't show up when I ran `cargo doc` - maybe because it's an impl for `Iterator`?

**Comment by jgallagher** [comment]
Closing this for now; I think we've done what we can.
